attendance_system/urls.py
"""sit_bemui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('backend/', include('backend.urls'))
]

handler404 = "attendance_system.views.page_not_found_view"

backend/urls.py
from django.urls import path

urlpatterns = [
]

main/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('form', views.form, name='form'),
    path('postform', views.postForm, name='postform'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('absen/<str:id>', views.absen, name='absen'),
    path('search', views.search, name='search'),
    path('postsearch', views.postsearch, name='postsearch'),
    path('faq', views.faq, name='faq')

]

user/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('signup', views.signUp, name='signup'),
    path('postsignup', views.postSignUp, name='postsignup'),
    path('signin', views.signIn, name='signin'),
    path('postsignin', views.postSignIn, name='postsignin'),
    path('logout', views.logout, name='logout'),
]

backend/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

attendance_system/views.py
from django.shortcuts import render

def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

backend/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render, redirect

from backend.CRUD.crud_attendance import attend_create, absent, attend_read
from django.contrib import auth
from django.http import Http404

from backend.CRUD.crud_jadwal import sbm_read_all, simak_read_all
from backend.CRUD.crud_user import user_read
from backend.constants.jadwal import jadwal_jenis, jadwal_id, dictJadwal
from backend.constants.jurusan import dictJurusan
from backend.misc import firebase_init, custom_qr

fauth = firebase_init

def index(request):
    return redirect("main:form")

# ---------------------
# Authentication
# --------------------
def form(request):
    jadwal_sbm = sbm_read_all()
    jadwal_simak = simak_read_all()
    return render(request, 'form.html', {
        'jadwal_sbm': jadwal_sbm,
        'jadwal_simak': jadwal_simak
    })

def postForm(request):
    nama = request.POST.get("nama")
    email = request.POST.get("email")
    telephone = request.POST.get("telephone")
    npm = request.POST.get("npm")
    fakultas = request.POST.get("fakultas")
    jurusan = request.POST.get(dictJurusan[fakultas])
    ukuran = request.POST.get("ukuran")
    jalur = request.POST.get("jalur")
    jadwal = request.POST.get(dictJadwal[jalur])

    idJadwal = jadwal_id[jadwal]
    jenisJadwal = jadwal_jenis[jadwal]

    message = attend_create(nama, telephone, email, npm, fakultas, jurusan, ukuran, jalur, jadwal, idJadwal, jenisJadwal)
    if (message != "terjadi error"):
        return redirect("detail/" + message)
    else:
        message = "gagal upload"
        return redirect("main:form")

def detail(request, id):
    data = attend_read(id)
    qr = custom_qr.get_qr("https://jaketkuningui2022.herokuapp.com/detail/" + id)
    if(data):
        return render(request, 'details.html', {
            'data': data,
            'id': id,
            'qr': qr,
        })
    else:
        raise Http404


def absen(request, id):
    absent(id)
    return redirect('main:detail', id=id)

def search(request):
        return render(request, 'cari.html')

def postsearch(request):
    npm = request.POST.get('npm')
    return redirect('main:detail', id=npm)

def faq(request):
    return render(request, 'faq.html')

user/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from backend.CRUD.crud_user import user_create, user_read
from django.contrib import auth
from backend.misc import firebase_init

fauth = firebase_init


# ---------------------
# Authentication
# --------------------
def signUp(request):
	try:
		if (request.session['uid']):
			user_session = fauth.get_account_info(request.session['uid'])
			if (user_session):
				user = user_read(user_session['users'][0]['email'])
				if (user['email'] == "admin_jakun@admin.com" or user['email'] == "mika@mika.com"):
					return render(request, 'signup.html')
	except:
			raise Http404


def postSignUp(request):
	email = request.POST.get("email")
	password = request.POST.get("password1")
	password2 = request.POST.get("password2")
	nama = request.POST.get("nama")
	if (password == password2):
		message = user_create(email, password, nama)
	if message == "":
		return redirect("user:signin")
	else:
		return redirect("user:signup")

def signIn(request):
	return render(request, 'signin.html')

def postSignIn(request):
	email = request.POST.get("email")
	password = request.POST.get("password")
	try:
		user = fauth.sign_in_with_email_and_password(email, password)
		print(user)
		session_id = user['idToken']
		request.session['uid'] = str(session_id)
		print(request.session['uid'])
		return redirect('/')
	except:
		return redirect(signIn)

def logout(request):
	auth.logout(request)
	return redirect("user:signin")

main/templates/cari.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Cari NPM</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}"/>
{% endblock meta %}
{% block content %}
    <div class="content-root">
        <div class="form-root">
            <h1 id="judul-form">Cari berdasarkan NPM</h1>
            <section>
                <form action="postsearch" method="post" id="form">
                    {% csrf_token %}
                    <label for="npm">NPM</label>
                    <input type="number" id="npm" name="npm" placeholder="NPM anda..."><br/>

                    <button type="submit" class="button" value="submit" id="submitbutton">Cari</button>
                </form>
            </section>
        </div>
    </div>
{% endblock content %}

main/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Detail Request</title>
    <link rel="stylesheet" href="{% static 'main/css/style-details.css' %}">
{% endblock meta %}

{% block content %}
    <div class="attention only-desktop">
        <h1 style="color: red">
            Mahasiswa Baru diwajibkan untuk membawa <br> Kartu Pemkes + Print Out IDM pada laman SIAK-NG <br> untuk verifikasi pengambilan
        </h1>
    </div>
    <div class="attention only-mobile">
        <h1 style="color: red">
            Mahasiswa Baru diwajibkan untuk membawa Kartu Pemkes + Print Out IDM pada laman SIAK-NG untuk verifikasi pengambilan
        </h1>
    </div>
<div class="content-root">
    <div class="details-judul detail-only-desktop">
        <div class="row">
            <div class="column">
                {% if data.absence == -1 %}
                    <object class="object" data="{% static 'main/svg/Depression-pana.svg' %}" type="image/svg+xml"></object>
                    <h1 >Belum Mengambil</h1>
                {% elif data.absence == 1 %}
                    <object class="object" data="{% static 'main/svg/Young_and_happy-pana.svg' %}" type="image/svg+xml"></object>
                    <h1>Sudah Mengambil</h1>
                {% endif %}
            </div>
            <div class="column">
                <h3>Screenshot QR ini<br>untuk pengambilan Jakun</h3>
                <img src="{{ qr }}">
            </div>
        </div>
    </div>

    <div class="details-judul detail-only-mobile">
        <div class="row">
            {% if data.absence == -1 %}
                <object class="object" data="{% static 'main/svg/Depression-pana.svg' %}" type="image/svg+xml"></object>
                <h1 >Belum Mengambil</h1>
            {% elif data.absence == 1 %}
                <object class="object" data="{% static 'main/svg/Young_and_happy-pana.svg' %}" type="image/svg+xml"></object>
                <h1>Sudah Mengambil</h1>
            {% endif %}
            <div class="filler"></div>
            <h2>Screenshot QR ini<br>untuk pengambilan Jakun</h2>
            <img src="{{ qr }}">
        </div>
    </div>

    <div class="details-info detail-only-desktop">
        <h1>Data Mahasiswa</h1>
        <br>
        <div class="row">
            <div class="column">
                <h3>Nama</h3>
                <p>{{ data.nama }}</p>
                <h3>Fakultas</h3>
                <p>{{ data.fakultas }}</p>
                <h3>Jurusan</h3>
                <p>{{ data.jurusan }}</p>
                <h3>NPM</h3>
                <p>{{ data.npm }}</p>
                <h3>Jalur Masuk</h3>
                <p>{{ data.jalur }}</p>
            </div>
            <div class="column">
                <h3>Kontak</h3>
                <p>{{ data.telepon }}<br>{{ data.email }}</p>
                <h3>Ukuran Jakun</h3>
                <p>{{ data.ukuran }}</p>
                <h3>Jadwal Pengambilan</h3>
                <p>{{ data.jadwal }}</p>
                <h3>Waktu Isi Form</h3>
                <p>{{ data.waktu_pengajuan }}</p>
                {% if data.absence == 1 %}
                    <h3>Waktu Pengambilan</h3>
                    <p>{{ data.waktu_pengambilan }}</p>
                    <h3>Pengabsen</h3>
                    <p>{{ data.pengabsen }}</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="details-info only-mobile">
        <h1>Data Pesanan</h1>
        <br>
        <h3>Nama</h3>
        <p>{{ data.nama }}</p>
        <h3>Fakultas</h3>
        <p>{{ data.fakultas }}</p>
        <h3>Jurusan</h3>
        <p>{{ data.jurusan }}</p>
        <h3>NPM</h3>
        <p>{{ data.npm }}</p>
        <h3>Jalur Masuk</h3>
        <p>{{ data.jalur }}</p>
        <h3>Kontak</h3>
        <p>{{ data.telepon }}<br>{{ data.email }}</p>
        <h3>Ukuran Jakun</h3>
        <p>{{ data.ukuran }}</p>
        <h3>Jadwal Pengambilan</h3>
        <p>{{ data.jadwal }}</p>
        <h3>Waktu Isi Form</h3>
        <p>{{ data.waktu_pengajuan }}</p>
        {% if data.absence == 1 %}
            <h3>Waktu Pengambilan</h3>
            <p>{{ data.waktu_pengambilan }}</p>
            <h3>Pengabsen</h3>
            <p>{{ data.pengabsen }}</p>
        {% endif %}
    </div>

    <div class="kontak-adkes">
        <br>
        <h1>Kontak Adkesma BEM UI 2022</h1>
        <div class="row">
            <ol>
                <li>Instragram: @bemui.adkesma</li>
                <li>OA Line: @adm0801n</li>
                <li>Twitter: @BEMUI_Adkesma</li>
                <li>Narahubung Jakun: <br>
                    <ul>
                        <li>Alex: (0851-5875-5854 || LINE: shirohachii)</li>
                        <li>Jenet: (0812-8706-7699 || LINE: jeanetteclarista)</li>
                        <li>Sena: (0858-0000-6797 || LINE: senaimamp)</li>
                    </ul>
                </li>
            </ol>
        </div>
    </div>

    <div class="button-outer">
        {% if data.absence == -1 %}
        <form action="../absen/{{ id }}" method="post">
            {% csrf_token %}
            <input name="id_request" type="hidden" value={{ id }}>
            <input name="nama" type="hidden" value={{ nama }}>
            <button class="button" type="submit">Hadir</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock content %}

main/templates/faq.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Detail Request</title>
    <link rel="stylesheet" href="{% static 'main/css/style-details.css' %}">
{% endblock meta %}

{% block content %}
<div class="content-root">
    <a href="{% url 'main:form' %}" id="button-kembali">&lt Kembali</a>

    <div class="details-info detail-only-desktop">
        <h1>Frequenly Asked Questions</h1>
        <br>
        <div class="row">
            <h3 style="margin-top: 4em">1. Apakah saya perlu mendaftarkan diri untuk mengambil jakun?</h3>
            <p>Mahasiswa Baru diwajibkan untuk mendaftar pada laman <a href="ui.id/JaketKuningUI2022">ui.id/JaketKuningUI2022</a></p>
            <h3 style="margin-top: 3em">2. Apakah pengambilan Jaket Kuning dapat diwakilkan?</h3>
            <p>Pengambilan Jaket Kuning 2022 hanya boleh dilakukan oleh Mahasiswa Baru yang bersangkutan dan tidak dapat diwakilkan oleh siapapun</p>
            <h3 style="margin-top: 3em">3. Apakah diperbolehkan mengambil jakun di luar jadwal yang telah ditentukan?</h3>
            <p>Para Mahasiswa Baru diharapkan untuk mengambil pada jadwal yang telah ditentukan. Pengambilan diluar jadwal hanya untuk dalam keadaan mendesak dengan disertai bukti yang valid</p>
            <h3 style="margin-top: 3em">4. Apa yang kami bawa saat pengambilan Jaket Kuning?</h3>
            <p>Mahasiswa Baru diwajibkan membawa Kartu Pemkes, Print Out IDM pada laman SIAK-NG masing-masing serta screenshot QR Code pada laman pengambilan Jaket Kuning</p>
            <h3 style="margin-top: 3em">5. Apakah mahasiswa baru dapat menukar ukuran jakun?</h3>
            <p>Pada proses verifikasi, ukuran jakun mahasiswa baru akan dicocokan dengan database IDM SIAK-NG. Jika terdapat perbedaan ukuran antara print out IDM dan database SIAK-NG, maka ukuran yang dipakai mengacu pada database SIAK-NG</p>
            <h3 style="margin-top: 3em">6. Apakah pembagian jakun hanya untuk mahasiswa S1 saja?</h3>
            <p>Pembagian jakun ini diperuntukan bagi semua jenjang dan program S1 dan Vokasi</p>
            <h3 style="margin-top: 3em">7. Di mana letak Annex?</h3>
            <p>Annex terletak di area Balairung Universitas Indonesia yang beralamat di Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424</p>
        </div>
    </div>
    <div class="details-info only-mobile">
        <h1>Frequenly Asked Questions</h1>
        <br>
        <div class="row">
            <h3 style="margin-top: 4em">1. Apakah saya perlu mendaftarkan diri untuk mengambil jakun?</h3>
            <p>Mahasiswa Baru diwajibkan untuk mendaftar pada laman <a href="http://ui.id/JaketKuningUI2022">ui.id/JaketKuningUI2022</a></p>
            <h3 style="margin-top: 3em">2. Apakah pengambilan Jaket Kuning dapat diwakilkan?</h3>
            <p>Pengambilan Jaket Kuning 2022 hanya boleh dilakukan oleh Mahasiswa Baru yang bersangkutan dan tidak dapat diwakilkan oleh siapapun</p>
            <h3 style="margin-top: 3em">3. Apakah diperbolehkan mengambil jakun di luar jadwal yang telah ditentukan?</h3>
            <p>Para Mahasiswa Baru diharapkan untuk mengambil pada jadwal yang telah ditentukan. Pengambilan diluar jadwal hanya untuk dalam keadaan mendesak dengan disertai bukti yang valid</p>
            <h3 style="margin-top: 3em">4. Apa yang kami bawa saat pengambilan Jaket Kuning?</h3>
            <p>Mahasiswa Baru diwajibkan membawa Kartu Pemkes, Print Out IDM pada laman SIAK-NG masing-masing serta screenshot QR Code pada laman pengambilan Jaket Kuning</p>
            <h3 style="margin-top: 3em">5. Apakah mahasiswa baru dapat menukar ukuran jakun?</h3>
            <p>Pada proses verifikasi, ukuran jakun mahasiswa baru akan dicocokan dengan database IDM SIAK-NG. Jika terdapat perbedaan ukuran antara print out IDM dan database SIAK-NG, maka ukuran yang dipakai mengacu pada database SIAK-NG</p>
            <h3 style="margin-top: 3em">6. Apakah pembagian jakun hanya untuk mahasiswa S1 saja?</h3>
            <p>Pembagian jakun ini diperuntukan bagi semua jenjang dan program S1 dan Vokasi</p>
            <h3 style="margin-top: 3em">7. Di mana letak Annex?</h3>
            <p>Annex terletak di area Balairung Universitas Indonesia yang beralamat di Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424</p>
        </div>
    </div>

    <div class="button-outer">
        {% if nama and data.absence == -1 %}
        <form action="../absen/{{ id }}" method="post">
            {% csrf_token %}
            <input name="id_request" type="hidden" value={{ id }}>
            <input name="nama" type="hidden" value={{ nama }}>
            <button class="button" type="submit">Hadir</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'base/img/favicon.png' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="application/javascript" src="{% static 'base/js/script.js' %}"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
	<header {% if '/' == request.path %}class="header-transparent"{% else %}class="header-white"{% endif %}>
        <a href="{% url 'main:form' %}" class="logo"><img src="{% static 'base/img/logo-biro-jodoh.png' %}" style="width:8.75rem; height:3.5rem;"></a>
        <input type="checkbox" class="nav-toggle" id="nav-toggle">

        <nav>
            <ul>
                <li>
                    <a href="{% url 'main:form' %}">Isi Form</a>
                </li>
                <li>
                    <a href="{% url 'main:search' %}">Cari NPM</a>
                </li>
            </ul>
        </nav>


        <label for="nav-toggle" class="nav-toggle-label" id="nav-toggle-label"><span></span></label>

    </header>

    <div class="content-container">
      	{% block content %}
        {% endblock content %}
	</div>

    <footer>
        <div class="footer-upper">
            <div class="footer1">
                <a href="{% url 'main:form' %}"><img src="{% static 'base/img/logo-biro-jodoh.png' %}" style="width:12.5rem; height:5rem;"></a>
            </div>
            <div class="footer3 nav-only-mobile">
                <p>
                    <svg width="24" height="24" viewBox="0 0 24 24">
                        <use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
                    </svg>
                    2022 - Badan Eksekutif Mahasiswa UI <br> Biro Multimedia x Departemen Adkesma
                </p>
            </div>
        </div>
        <div class="footer-bottom nav-only-desktop">
            <div>
                <svg width="24" height="24" viewBox="0 0 24 24">
                    <use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
                </svg>
                <p>2022 - Badan Eksekutif Mahasiswa UI <br> Biro Multimedia x Departemen Adkesma</p>
            </div>
        </div>
    </footer>
</body>

</html>

user/templates/signin.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}"/>
{% endblock meta %}

{% block content %}
    <div class="attention">
        <h1 style="color: red">
            Perhatian! <br>Laman ini khusus untuk Panitia Jakun 2022
        </h1>
    </div>
<div class="content-root">
    <div class="form-root">
        <h1 id="judul-form">Sign In</h1>
        <section>
            <form action="postsignin" method="post" id="form">
            {% csrf_token %}
                <label for="email" >Email</label>
                <input type="email" name="email" id="email" placeholder="Masukkan email anda..."> <br/>

                <label for="password" >Password</label>
                <input type="password" name="password" id="password" placeholder="Masukkan password anda..."><br/>

                <button type="submit" class="button" value="SignIn" id="submitbutton">Sign In</button>
            </form>
        </section>
    </div>
    <object class="object only-desktop" data="{% static 'user/svg/Computer-login-amico.svg' %}" type="image/svg+xml"></object>
</div>
{% endblock content %}

user/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}"/>
{% endblock meta %}

{% block content %}
<div class="content-root">
    <div class="form-root">
        <h1 id="judul-form">Sign Up</h1>
        <section>
            <form action="postsignup" method="post" id="form">
            {% csrf_token %}
                <label for="email">Email</label>
                <input type="email" name="email" id="email" placeholder="Masukkan email..."><br/>

                <label for="password1">Password</label>
                <input type="password" name="password1" id="password1" placeholder="Masukkan password..."><br/>

                <label for="password2">Ulang password</label>
                <input type="password" name="password2" id="password2" placeholder="Ulangi password..."><br/>

                <label for="name">Nama</label>
                <input type="text" name="nama" id="name" placeholder="Masukkan nama anda..."><br/>

                <button type="submit" class="button" value="SignUp" id="submitbutton">Sign Up</button>
            </form>
        </section>
    </div>
    <object class="object only-desktop" data="{% static 'user/svg/Computer-login-amico.svg' %}" type="image/svg+xml"></object>
</div>
{% endblock content %}